---
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
  bandit:
    enabled: true
exclude_patterns:
- debian/
- doc/
- setup/
